subgraphs:
    characters:
      routing_url: http://localhost:4002/graphql
      schema:
        file: ./subgraphs/characters/src/schema.graphql
    species:
      routing_url: http://localhost:4001/graphql
      schema:
        file: ./subgraphs/species/src/schema.graphql
