service: swapi-apollo-federation-characters
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  stackName: ${opt:stage, 'dev'}-${self:service}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  webpack:
    webpackConfig: "webpack.config.js" # Name of webpack configuration file
    includeModules: false # Node modules configuration for packaging
    packager: "npm" # Packager that will be used to package your external modules

functions:
  lambda:
    handler: src/server.graphqlHandler
    memorySize: 128
    description: The Apollo characters subgraph.
    timeout: 30
